# Generated by Django 3.0.8 on 2020-07-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0003_auto_20200731_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picha.Locations'),
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picha.Categories'),
        ),
    ]
