# Generated by Django 3.0.8 on 2020-07-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0004_auto_20200731_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Location',
            new_name='location',
        ),
    ]
